FROM maven:3.8-openjdk-11-slim as builder

WORKDIR /app

COPY pom.xml .

RUN mvn -B -f pom.xml dependency:go-offline
# Copy all other project files and build project
COPY . /app
RUN mvn -B install -DskipTests=true

FROM openjdk:11-slim

WORKDIR /app

COPY --from=builder /app/target/*.jar /app

ENTRYPOINT ["mvn", "test" ]
